const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const counsel = fs.readFileSync(path.join(root, "counsel", "index.html"), "utf8");
const reserve = fs.readFileSync(path.join(root, "assets", "js", "reserve.js"), "utf8");
const main = fs.readFileSync(path.join(root, "gas", "99_Main.gs"), "utf8");
const workflow = fs.readFileSync(path.join(root, "gas", "88_DietCounselingWorkflow.gs"), "utf8");
const form = fs.readFileSync(path.join(root, "diet-counseling", "app.js"), "utf8");
const formHtml = fs.readFileSync(path.join(root, "diet-counseling", "index.html"), "utf8");
const formStyles = fs.readFileSync(path.join(root, "diet-counseling", "styles.css"), "utf8");
const admin = fs.readFileSync(path.join(root, "admin", "admin-counseling-links.js"), "utf8");

assert.match(counsel, /name="consultation_method" value="ONLINE" checked/);
assert.match(counsel, /name="consultation_method" value="IN_PERSON"/);
assert.doesNotMatch(counsel, /どちらでもよい/);
assert.match(reserve, /consultation_method:\s*getConsultationMethod_\(\)/);
assert.match(reserve, /searchParams\.set\("consultation_method", getConsultationMethod_\(\)\)/);

assert.match(main, /getDietCounselingAvailableSlots_\(params\)/);
assert.match(main, /getDietCounselingAvailableSlotsRange_\(params\)/);
assert.match(main, /createDietCounselingReservation_\(body\)/);
assert.match(main, /getDietCounselingFormContext_\(params\)/);
assert.match(main, /getDietCounselingStaffSheet_\(params\)/);
assert.match(main, /submitDietCounselingResponse_\(body\)/);
assert.match(main, /sendDietCounselingLinksBulk_\(body\)/);
assert.match(main, /function validatePersonalPreviousDayBookingCutoff_/);
assert.match(main, /PERSONAL_BOOKING_CUTOFF/);

assert.match(workflow, /OFFICE_STORE_CODE:\s*"HEAD_OFFICE"/);
assert.match(workflow, /ANSWER_SPREADSHEET_ID:\s*"1muAm2zWPhI7NU3AA1vrd2ygKUqDh9ix6KFDATk9mX90"/);
assert.match(workflow, /getDietCounselingHeaderMap_/);
assert.match(workflow, /FORM_VERSION:\s*"1\.3"/);
assert.match(workflow, /不足：/);
assert.match(workflow, /重複：/);
assert.match(workflow, /MailApp\.sendEmail/);
assert.match(workflow, /ONLINE_ONLY_START_TIME:\s*"19:00"/);
assert.match(workflow, /ONLINE_ONLY_LAST_START_TIME:\s*"22:00"/);
assert.match(workflow, /ONLINE_ONLY_END_TIME:\s*"23:00"/);
assert.match(workflow, /ONLINE_ONLY_TRAVEL_MINUTES:\s*150/);
assert.match(workflow, /ensureDietCounselingAnswerHeaders_/);
assert.doesNotMatch(
  workflow.match(/function getDietCounselingFormContext_[\s\S]*?\n}\n/)[0],
  /print_sheet/
);

assert.match(form, /getDietCounselingFormContext/);
assert.match(form, /submitDietCounselingResponse/);
assert.match(form, /showCounselingSheet/);
assert.match(form, /getDietCounselingStaffSheet/);
assert.match(form, /view_token/);
assert.match(form, /preparePrintLayout/);
assert.match(form, /dataset\.printScale/);
assert.match(form, /window\.print\(\)/);
assert.match(form, /sheetValue\(sheet\.name, " 様"\)/);
assert.match(form, /class="sheet-rhythm-grid"/);
assert.match(form, />仕事のとき</);
assert.match(form, />休みのとき</);
assert.match(form, /sheetItem\("就寝", sheet\.sleep_work\)/);
assert.match(form, /sheetItem\("起床", sheet\.wake_work\)/);
assert.match(form, /sheetItem\("睡眠時間", sheet\.sleep_hours_work, " 時間"\)/);
assert.match(form, /preview"\) === "sheet"/);
assert.match(form, /minutes < 24 \* 60; minutes \+= 15/);
assert.match(form, /!TOKEN && !ADMIN_VIEW_TOKEN && !IS_SHEET_PREVIEW && !IS_PRINT_PREVIEW/);
assert.match(form, /if \(!IS_PREVIEW && !validateStep\(currentStep\)\) return/);
assert.match(form, /確認用プレビューのため、回答は送信されません/);
assert.match(formHtml, /id="previewModeBanner"/);
assert.match(formHtml, /id="counselingSheetScreen"/);
assert.match(formHtml, /id="printSheetButton"/);
assert.match(formHtml, /id="printPage"/);
assert.match(formHtml, />管理者用</);
assert.match(formHtml, /印刷する/);
assert.match(formStyles, /\.page-shell\[hidden\]/);
assert.match(formStyles, /@media print/);
assert.match(formStyles, /@page \{ size: A4 portrait;/);
assert.match(formStyles, /body\.is-print-layout \.print-page/);
assert.match(formStyles, /height:\s*286mm/);
assert.match(formStyles, /\.sheet-rhythm-grid \{[^}]*grid-template-columns:\s*repeat\(3,/);
assert.match(formStyles, /\.sheet-food-notes \{[^}]*grid-template-columns:\s*repeat\(2,/);
assert.match(formStyles, /@media screen and \(max-width: 680px\)/);
assert.match(formStyles, /body\.is-print-layout \.print-page \{[\s\S]*?width:\s*100%;[\s\S]*?height:\s*auto;/);
assert.match(formStyles, /body\.is-print-layout \.print-sheet \{[\s\S]*?width:\s*100% !important;[\s\S]*?transform:\s*none !important;/);
assert.match(formStyles, /body\.is-print-layout \.sheet-content-grid \{ grid-template-columns:\s*1fr;/);
assert.doesNotMatch(form, /UI確認版のため/);
assert.match(formHtml, /<option value="男性">男性<\/option><option value="女性">女性<\/option>/);
assert.doesNotMatch(formHtml, /その他・回答しない/);
assert.doesNotMatch(formHtml, /The Forest Gym/);
assert.doesNotMatch(form, /The Forest Gym/);
assert.match(formHtml, /ご記入時のお願い/);
assert.match(formHtml, /ごはん、みそ汁、サラダ、から揚げ、湯豆腐、マグロ刺身、焼き鮭/);
assert.match(formHtml, /コンビニ弁当、定食、丼物、麺類、自炊/);
assert.match(formHtml, /id="exercise_history_detail"[^>]*required/);
assert.match(formHtml, /id="current_exercise_detail"[^>]*required/);
assert.match(formHtml, /id="medical_history_detail"[^>]*required/);
assert.match(formHtml, /id="diet_experience_period"[^>]*required/);
assert.match(formHtml, /id="diet_experience_method"[^>]*required/);
assert.match(formHtml, /id="diet_experience_result"[^>]*required/);
assert.match(formHtml, /運動内容・頻度・1回あたりの時間/);
assert.match(formHtml, /病名・時期・現在の状況/);
assert.match(formHtml, /どのような方法で？/);
assert.match(formHtml, /成果/);
assert.match(workflow, /buildDietCounselingPrintSheetData_/);
assert.match(workflow, /PDF不要（管理画面印刷）/);
assert.doesNotMatch(counsel, /The Forest Gymまたは本社事務所から/);
assert.doesNotMatch(counsel, /The Forest Gymで実施します/);
assert.doesNotMatch(reserve, /The Forest Gymで対面対応可能な日程/);
assert.match(admin, /getDietCounselingLinkCandidates/);
assert.match(admin, /sendDietCounselingLinksBulk/);
assert.match(admin, /window\.confirm/);

console.log("diet counseling UI integration tests passed");
