const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = path.join(__dirname, "..");
const counsel = fs.readFileSync(path.join(root, "counsel", "index.html"), "utf8");
const reserve = fs.readFileSync(path.join(root, "assets", "js", "reserve.js"), "utf8");
const main = fs.readFileSync(path.join(root, "gas", "99_Main.gs"), "utf8");
const workflow = fs.readFileSync(path.join(root, "gas", "88_DietCounselingWorkflow.gs"), "utf8");
const form = fs.readFileSync(path.join(root, "diet-counseling", "app.js"), "utf8");
const formHtml = fs.readFileSync(path.join(root, "diet-counseling", "index.html"), "utf8");
const formStyles = fs.readFileSync(path.join(root, "diet-counseling", "styles.css"), "utf8");
const admin = fs.readFileSync(path.join(root, "admin", "admin-counseling-links.js"), "utf8");

assert.match(counsel, /name="consultation_method" value="ONLINE" checked/);
assert.match(counsel, /name="consultation_method" value="IN_PERSON"/);
assert.doesNotMatch(counsel, /どちらでもよい/);
assert.match(reserve, /consultation_method:\s*getConsultationMethod_\(\)/);
assert.match(reserve, /searchParams\.set\("consultation_method", getConsultationMethod_\(\)\)/);

assert.match(main, /getDietCounselingAvailableSlots_\(params\)/);
assert.match(main, /getDietCounselingAvailableSlotsRange_\(params\)/);
assert.match(main, /createDietCounselingReservation_\(body\)/);
assert.match(main, /getDietCounselingFormContext_\(params\)/);
assert.match(main, /submitDietCounselingResponse_\(body\)/);
assert.match(main, /sendDietCounselingLinksBulk_\(body\)/);

assert.match(workflow, /OFFICE_STORE_CODE:\s*"HEAD_OFFICE"/);
assert.match(workflow, /ANSWER_SPREADSHEET_ID:\s*"1muAm2zWPhI7NU3AA1vrd2ygKUqDh9ix6KFDATk9mX90"/);
assert.match(workflow, /getDietCounselingHeaderMap_/);
assert.match(workflow, /FORM_VERSION:\s*"1\.2"/);
assert.match(workflow, /不足：/);
assert.match(workflow, /重複：/);
assert.match(workflow, /MailApp\.sendEmail/);

assert.match(form, /getDietCounselingFormContext/);
assert.match(form, /submitDietCounselingResponse/);
assert.match(form, /showCounselingSheet/);
assert.match(form, /window\.print\(\)/);
assert.match(form, /preview"\) === "sheet"/);
assert.match(form, /minutes < 24 \* 60; minutes \+= 15/);
assert.match(form, /const IS_PREVIEW = QUERY\.get\("preview"\) === "1" \|\| !QUERY\.has\("token"\)/);
assert.match(form, /if \(!IS_PREVIEW && !validateStep\(currentStep\)\) return/);
assert.match(form, /確認用プレビューのため、回答は送信されません/);
assert.match(formHtml, /id="previewModeBanner"/);
assert.match(formHtml, /id="counselingSheetScreen"/);
assert.match(formHtml, /id="printSheetButton"/);
assert.match(formHtml, /印刷する/);
assert.match(formStyles, /\.page-shell\[hidden\]/);
assert.match(formStyles, /@media print/);
assert.doesNotMatch(form, /UI確認版のため/);
assert.match(formHtml, /<option value="男性">男性<\/option><option value="女性">女性<\/option>/);
assert.doesNotMatch(formHtml, /その他・回答しない/);
assert.doesNotMatch(formHtml, /The Forest Gym/);
assert.doesNotMatch(form, /The Forest Gym/);
assert.match(formHtml, /ご記入時のお願い/);
assert.match(formHtml, /ごはん、みそ汁、サラダ、から揚げ、湯豆腐、マグロ刺身、焼き鮭/);
assert.match(formHtml, /コンビニ弁当、定食、丼物、麺類、自炊/);
assert.match(formHtml, /id="exercise_history_detail"[^>]*required/);
assert.match(formHtml, /id="current_exercise_detail"[^>]*required/);
assert.match(formHtml, /id="medical_history_detail"[^>]*required/);
assert.match(formHtml, /id="diet_experience_period"[^>]*required/);
assert.match(formHtml, /id="diet_experience_method"[^>]*required/);
assert.match(formHtml, /id="diet_experience_result"[^>]*required/);
assert.match(formHtml, /運動内容・頻度・1回あたりの時間/);
assert.match(formHtml, /病名・時期・現在の状況/);
assert.match(formHtml, /どのような方法で？/);
assert.match(formHtml, /成果/);
assert.match(workflow, /buildDietCounselingPrintSheetData_/);
assert.match(workflow, /PDF不要（印刷画面）/);
assert.doesNotMatch(counsel, /The Forest Gymまたは本社事務所から/);
assert.match(counsel, /The Forest Gymで実施/);
assert.doesNotMatch(reserve, /The Forest Gymで対面対応可能な日程/);\nassert.match(reserve, /対面はThe Forest Gymで実施します/);
assert.match(admin, /getDietCounselingLinkCandidates/);
assert.match(admin, /sendDietCounselingLinksBulk/);
assert.match(admin, /window\.confirm/);

console.log("diet counseling UI integration tests passed");
