const API_URL="https://script.google.com/macros/s/AKfycbyvpQRxRpMRfpaQHtBar77dViCqPl-hdFW-2yMdozhN8RHtwcrFiNEM9cvEbny4x9q0/exec";
const state={staff:[],selectedStaffCode:""};
const roleMeta={OWNER:{icon:"👑",label:"OWNER"},TRAINER:{icon:"🏋️",label:"TRAINER"},STAFF:{icon:"👤",label:"STAFF"}};
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const el={staffManager:$("#staffManager"),registrationPlaceholder:$("#registrationPlaceholder"),placeholderIcon:$("#placeholderIcon"),placeholderTitle:$("#placeholderTitle"),staffList:$("#staffList"),staffSearch:$("#staffSearch"),newStaffButton:$("#newStaffButton"),staffForm:$("#staffForm"),staffFormTitle:$("#staffFormTitle"),staffCodeDisplay:$("#staffCodeDisplay"),staffFormMessage:$("#staffFormMessage"),saveStaffButton:$("#saveStaffButton"),staffName:$("#staffName"),displayName:$("#displayName"),romanSurname:$("#romanSurname"),brandCode:$("#brandCode"),storeCode:$("#storeCode"),role:$("#role"),email:$("#email"),calendarCode:$("#calendarCode"),mailAccountCode:$("#mailAccountCode"),color:$("#color"),colorText:$("#colorText"),active:$("#active"),canPersonal:$("#canPersonal"),canTour:$("#canTour"),canCounsel:$("#canCounsel"),canMealPlanning:$("#canMealPlanning"),canTrainingSupport:$("#canTrainingSupport"),canProcedure:$("#canProcedure"),canUnsubscribe:$("#canUnsubscribe"),can9Round:$("#can9Round")};
$$('.nav-button').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.view;$$('.nav-button').forEach(x=>x.classList.toggle('is-active',x===b));$$('.view').forEach(x=>x.classList.remove('is-active'));$('#'+v+'View').classList.add('is-active')}));
$$('.registration-card').forEach(b=>b.addEventListener('click',()=>showRegistration(b.dataset.registration)));
el.staffSearch.addEventListener('input',renderStaffList);el.newStaffButton.addEventListener('click',resetStaffForm);el.staffForm.addEventListener('submit',saveStaff);el.color.addEventListener('input',()=>el.colorText.value=el.color.value.toUpperCase());el.colorText.addEventListener('input',()=>{if(/^#[0-9A-Fa-f]{6}$/.test(el.colorText.value))el.color.value=el.colorText.value});
async function showRegistration(type){el.staffManager.classList.add('is-hidden');el.registrationPlaceholder.classList.add('is-hidden');if(type==='staff'){el.staffManager.classList.remove('is-hidden');await loadStaff();resetStaffForm();return}const labels={shift:['🗓️','シフト登録'],service:['🏷️','サービス登録'],hours:['🕒','サービス提供時間'],mailTemplate:['✉️','メールテンプレート'],calendar:['📆','カレンダー'],mailAccount:['📧','メールアカウント']};const [i,t]=labels[type]||['🛠️','準備中'];el.placeholderIcon.textContent=i;el.placeholderTitle.textContent=t;el.registrationPlaceholder.classList.remove('is-hidden')}
async function loadStaff(){el.staffList.innerHTML='<div class="loading-row">読み込み中…</div>';try{const u=new URL(API_URL);u.searchParams.set('action','getStaff');u.searchParams.set('include_inactive','true');u.searchParams.set('_',Date.now());const r=await fetch(u,{cache:'no-store'});const j=await r.json();if(!j.ok)throw new Error(j.message||'取得失敗');state.staff=Array.isArray(j.data?.staff)?j.data.staff:Array.isArray(j.data)?j.data:[];renderStaffList()}catch(e){el.staffList.innerHTML=`<div class="no-staff">${escapeHtml(e.message)}</div>`}}
function renderStaffList(){const q=el.staffSearch.value.trim().toLowerCase();const list=state.staff.filter(s=>[s.staff_code,s.staff_name,s.display_name,s.role,s.store_code].join(' ').toLowerCase().includes(q));if(!list.length){el.staffList.innerHTML='<div class="no-staff">該当するスタッフがいません。</div>';return}el.staffList.replaceChildren();list.forEach(s=>{const m=roleMeta[String(s.role||'').toUpperCase()]||roleMeta.STAFF;const b=document.createElement('button');b.type='button';b.className='staff-card';b.classList.toggle('is-selected',s.staff_code===state.selectedStaffCode);b.innerHTML=`<span class="role-icon">${m.icon}</span><span class="staff-meta"><strong>${escapeHtml(s.display_name||s.staff_name||s.staff_code)}</strong><small>${m.label} · ${escapeHtml(s.store_code||'')}</small></span><span class="staff-color" style="background:${escapeHtml(s.color||'#94a3b8')}"></span>`;b.onclick=()=>selectStaff(s.staff_code);el.staffList.append(b)})}
function selectStaff(code){const s=state.staff.find(x=>x.staff_code===code);if(!s)return;state.selectedStaffCode=code;el.staffFormTitle.textContent=s.staff_name||'スタッフ編集';el.staffCodeDisplay.textContent=`スタッフコード：${s.staff_code}（変更不可）`;el.staffName.value=s.staff_name||'';el.displayName.value=s.display_name||'';el.romanSurname.value='';el.romanSurname.disabled=true;el.brandCode.value=s.brand_code||'TFG';el.storeCode.value=s.store_code||'YACHIYO';el.role.value=s.role||'STAFF';el.email.value=s.email||'';el.calendarCode.value=s.calendar_code||'';el.mailAccountCode.value=s.mail_account_code||'';el.color.value=/^#[0-9A-Fa-f]{6}$/.test(s.color||'')?s.color:'#2563eb';el.colorText.value=el.color.value.toUpperCase();el.active.checked=!!s.active;el.canPersonal.checked=!!s.can_personal;el.canTour.checked=!!s.can_tour;el.canCounsel.checked=!!s.can_counsel;el.canMealPlanning.checked=!!s.can_meal_planning;el.canTrainingSupport.checked=!!s.can_training_support;el.canProcedure.checked=!!s.can_procedure;el.canUnsubscribe.checked=!!s.can_unsubscribe;el.can9Round.checked=!!s.can_9round;hideMessage();renderStaffList()}
function resetStaffForm(){state.selectedStaffCode='';el.staffForm.reset();el.staffFormTitle.textContent='新規スタッフ';el.staffCodeDisplay.textContent='スタッフコードは姓（ローマ字）から自動生成されます。';el.romanSurname.disabled=false;el.brandCode.value='TFG';el.storeCode.value='YACHIYO';el.role.value='STAFF';el.color.value='#2563eb';el.colorText.value='#2563EB';el.active.checked=true;hideMessage();renderStaffList()}
async function saveStaff(e){e.preventDefault();hideMessage();let code=state.selectedStaffCode;if(!code){const base=normalizeCode(el.romanSurname.value);if(!base){showMessage('姓（ローマ字）を入力してください。',true);return}code=uniqueCode(base)}const p={action:'saveStaff',staff_code:code,brand_code:el.brandCode.value,store_code:el.storeCode.value,staff_name:el.staffName.value.trim(),display_name:el.displayName.value.trim(),email:el.email.value.trim(),calendar_code:el.calendarCode.value.trim(),mail_account_code:el.mailAccountCode.value.trim(),color:el.colorText.value.trim().toUpperCase(),role:el.role.value,active:el.active.checked,can_personal:el.canPersonal.checked,can_tour:el.canTour.checked,can_counsel:el.canCounsel.checked,can_meal_planning:el.canMealPlanning.checked,can_training_support:el.canTrainingSupport.checked,can_procedure:el.canProcedure.checked,can_unsubscribe:el.canUnsubscribe.checked,can_9round:el.can9Round.checked};el.saveStaffButton.disabled=true;el.saveStaffButton.textContent='保存中…';try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(p)});const j=await r.json();if(!j.ok)throw new Error(j.message||'保存失敗');showMessage(j.message||'保存しました。');await loadStaff();selectStaff(code)}catch(err){showMessage(err.message||'保存に失敗しました。',true)}finally{el.saveStaffButton.disabled=false;el.saveStaffButton.textContent='保存'}}
function uniqueCode(base){const set=new Set(state.staff.map(s=>String(s.staff_code||'').toUpperCase()));if(!set.has(base))return base;let n=2;while(set.has(base+n))n++;return base+n}function normalizeCode(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'')}function showMessage(m,e=false){el.staffFormMessage.textContent=m;el.staffFormMessage.classList.remove('is-hidden');el.staffFormMessage.classList.toggle('is-error',e)}function hideMessage(){el.staffFormMessage.textContent='';el.staffFormMessage.classList.add('is-hidden');el.staffFormMessage.classList.remove('is-error')}function escapeHtml(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}

function setTodayLabel(){
  const node=document.querySelector("#todayLabel");
  if(!node)return;
  const now=new Date();
  const weekdays=["日","月","火","水","木","金","土"];
  node.textContent=`${now.getFullYear()}/${String(now.getMonth()+1).padStart(2,"0")}/${String(now.getDate()).padStart(2,"0")}（${weekdays[now.getDay()]}）`;
}
