// Admin v57 extension: management my-shift direct edit + monthly schedule
(()=>{
  const originalApplyPermissionUi=applyPermissionUi;
  applyPermissionUi=function(){originalApplyPermissionUi();if(state.authUser?.staff_code)$("#myShiftNav")?.classList.remove("is-hidden");ensureMonthlyScheduleUi_();};
  canUseMyShift=function(){return authEnabled()&&!!state.authUser?.staff_code;};
  const originalLoadMyShiftView=loadMyShiftView;
  loadMyShiftView=async function(){if(!canUseMyShift())return;if(!isManagementUser())return originalLoadMyShiftView();const role=String(state.authUser?.role||"STAFF").toUpperCase(),raw=String(state.authUser?.display_name||state.authUser?.staff_name||state.authUser?.staff_code||"").trim(),name=role==="TRAINER"?`${raw}トレーナー`:`${raw}さん`;$("#myShiftPageTitle").textContent=`${name}のシフト`;if(!state.myShiftMonth)state.myShiftMonth=localYmd().slice(0,7);const range=monthRangeFromYm_(state.myShiftMonth);$("#myShiftMonthLabel").textContent=formatMonthLabel_(state.myShiftMonth);setupMyShiftMonthTabs_();$("#myShiftRequestForm")?.classList.add("is-hidden");$("#myShiftList").innerHTML='<div class="registered-shift-empty">読み込んでいます…</div>';try{const j=await apiGet("getStaffShifts",{staff_code:state.authUser.staff_code,start_date:range.start,end_date:range.end});state.myShiftRows=(Array.isArray(j.data)?j.data:j.data?.shifts||[]).filter(r=>r.active!==false).sort((a,b)=>String(a.date).localeCompare(String(b.date))||String(a.start_time).localeCompare(String(b.start_time)));renderManagementMyShiftRows_();$("#myShiftStatusSummary").textContent=`勤務 ${state.myShiftRows.length}件 / 直接編集`;$("#myShiftRequestHistory").innerHTML='<div class="registered-shift-empty">ADMIN / MANAGERは変更申請不要です。</div>';}catch(e){$("#myShiftList").innerHTML=`<div class="registered-shift-empty is-error">${esc(e.message)}</div>`;}};
  function renderManagementMyShiftRows_(){const box=$("#myShiftList"),rows=state.myShiftRows||[];if(!rows.length){box.innerHTML='<div class="registered-shift-empty">この月の確定シフトはありません。</div>';return;}box.innerHTML=rows.map(r=>`<div class="registered-shift-row"><div class="registered-shift-time"><strong>${esc(formatStaffDate(r.date))}</strong></div><div class="registered-shift-meta"><span>${esc(r.start_time)}〜${esc(r.end_time)}</span><small>${esc(r.store_code||"")}</small></div><div class="registered-shift-actions"><button class="ghost-button" data-adm-edit="${esc(r.shift_id)}">直接変更</button><button class="danger-ghost" data-adm-del="${esc(r.shift_id)}">直接削除</button></div></div>`).join("");$$('[data-adm-edit]').forEach(b=>b.onclick=()=>directEdit_(rows.find(r=>String(r.shift_id)===String(b.dataset.admEdit))));$$('[data-adm-del]').forEach(b=>b.onclick=()=>directDelete_(rows.find(r=>String(r.shift_id)===String(b.dataset.admDel))));}
  async function directEdit_(r){const s=prompt("開始時刻",String(r.start_time).slice(0,5));if(s===null)return;const e=prompt("終了時刻",String(r.end_time).slice(0,5));if(e===null)return;if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(s)||!/^([01]\d|2[0-3]):[0-5]\d$/.test(e)||s>=e)return alert("時刻を正しく入力してください。");if(!confirm(`${r.date} ${s}〜${e} に直接更新します。`))return;try{await apiPost({action:"saveStaffShift",shift_id:r.shift_id,staff_code:state.authUser.staff_code,store_code:r.store_code||state.authUser.store_code||"YACHIYO",date:r.date,start_time:s,end_time:e});await loadMyShiftView();}catch(x){alert(x.message)}}
  async function directDelete_(r){if(!confirm(`${r.date} ${r.start_time}〜${r.end_time} を直接削除します。`))return;try{await apiPost({action:"deleteStaffShift",shift_id:r.shift_id});await loadMyShiftView();}catch(x){alert(x.message)}}
  function ensureMonthlyScheduleUi_(){if($("#monthlyScheduleNav"))return;const my=$("#myShiftNav");if(!my)return;const n=document.createElement("button");n.id="monthlyScheduleNav";n.className="nav-button";n.dataset.view="monthlySchedule";n.innerHTML='<span>📅</span>予定一覧';my.before(n);const sec=document.createElement("section");sec.id="monthlyScheduleView";sec.className="view";sec.innerHTML=`<div class="page-heading"><div><p class="eyebrow">MONTHLY SCHEDULE</p><h1>予定一覧</h1><p>月単位で予定を確認できます。</p></div></div><div class="schedule-toolbar card"><div class="toolbar-group"><button id="monthlyPrev" class="icon-button">‹</button><button id="monthlyToday" class="ghost-button">今月</button><button id="monthlyNext" class="icon-button">›</button></div><strong id="monthlyLabel" class="period-title"></strong><select id="monthlyPersonFilter" style="min-width:210px"></select></div><div id="monthlyBoard" class="schedule-board card"></div>`;document.querySelector("main.main").appendChild(sec);state.monthlyScheduleMonth=state.monthlyScheduleMonth||localYmd().slice(0,7);n.onclick=async()=>{$$(".nav-button").forEach(x=>x.classList.toggle("is-active",x===n));$$(".view").forEach(x=>x.classList.remove("is-active"));sec.classList.add("is-active");await loadMonthly_();};$("#monthlyPrev").onclick=()=>moveMonthly_(-1);$("#monthlyNext").onclick=()=>moveMonthly_(1);$("#monthlyToday").onclick=()=>{state.monthlyScheduleMonth=localYmd().slice(0,7);loadMonthly_()};$("#monthlyPersonFilter").onchange=renderMonthly_;}
  function moveMonthly_(d){const r=monthRangeFromYm_(state.monthlyScheduleMonth),x=new Date(r.year,r.month-1+d,1);state.monthlyScheduleMonth=`${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}`;loadMonthly_();}
  async function loadMonthly_(){const ym=state.monthlyScheduleMonth,range=monthRangeFromYm_(ym);$("#monthlyLabel").textContent=formatMonthLabel_(ym);$("#monthlyBoard").innerHTML='<div class="staff-schedule-loading">1か月分を読み込んでいます…</div>';try{if(!state.staff.length){const j=await apiGet("getStaff",{include_inactive:"false"});state.staff=Array.isArray(j.data?.staff)?j.data.staff:Array.isArray(j.data)?j.data:[]}setupFilter_();const days=Array.from({length:range.last},(_,i)=>`${ym}-${String(i+1).padStart(2,"0")}`);state.monthlyScheduleData=await Promise.all(days.map(async date=>{const [s,t]=await Promise.all([apiGet("getStaffSchedule",{date,store_code:"YACHIYO"}),apiGet("getTrainerSchedule",{date,store_code:"YACHIYO"})]);return{date,s:s.data||{},t:t.data||{}}}));renderMonthly_()}catch(e){$("#monthlyBoard").innerHTML=`<div class="staff-schedule-empty"><strong>取得できませんでした</strong><span>${esc(e.message)}</span></div>`}}
  function setupFilter_(){const sel=$("#monthlyPersonFilter"),old=sel.value||"ALL",a=state.staff.filter(s=>s.active!==false),opts=[["ALL","全員"],["STAFF_ALL","スタッフ全員"],["TRAINER_ALL","トレーナー全員"],["SELF","自分"],...a.map(s=>[String(s.staff_code),roleHonorific(s)])];sel.innerHTML=opts.map(x=>`<option value="${esc(x[0])}">${esc(x[1])}</option>`).join("");if(opts.some(x=>x[0]===old))sel.value=old;}
  function match_(c,r,f){if(f==="ALL")return true;if(f==="SELF")return String(c)===String(state.authUser?.staff_code);if(f==="STAFF_ALL")return String(r).toUpperCase()==="STAFF";if(f==="TRAINER_ALL")return String(r).toUpperCase()==="TRAINER";return String(c)===f;}
  function renderMonthly_(){const box=$("#monthlyBoard"),f=$("#monthlyPersonFilter").value,map=new Map(state.staff.map(s=>[String(s.staff_code),s])),out=[];for(const d of state.monthlyScheduleData||[]){const sm=new Map(),rm=new Map();for(const r of [...(d.s.shifts||[]),...(d.t.shifts||[])])sm.set(`${r.staff_code}|${r.start_time}|${r.end_time}`,r);for(const r of [...(d.s.reservations||[]),...(d.t.reservations||[])].filter(x=>String(x.status||"").toUpperCase()!=="CANCELLED"))rm.set(String(r.reservation_id||`${r.staff_code}|${r.start_time}|${r.service_code}`),r);const rows=[];for(const r of sm.values()){const p=map.get(String(r.staff_code))||r;if(match_(r.staff_code,p.role,f))rows.push([r.start_time,roleHonorific(p),"勤務シフト"])}for(const r of rm.values()){const p=map.get(String(r.staff_code))||r;if(match_(r.staff_code,p.role,f))rows.push([r.start_time,roleHonorific(p),`${r.service_name||r.service_code} / ${r.customer_name||"氏名未登録"}`])}if(rows.length){rows.sort();out.push(`<section class="staff-day-section"><div class="staff-day-head"><strong>${esc(formatStaffDate(d.date))}</strong><span class="shift-pill">${rows.length}件</span></div><div class="staff-reservation-list">${rows.map(r=>`<div class="staff-reservation-row"><div class="staff-reservation-time">${esc(r[0])}</div><div class="staff-reservation-service"><strong>${esc(r[1])}</strong></div><div class="staff-reservation-customer"><strong>${esc(r[2])}</strong></div></div>`).join("")}</div></section>`)}}box.innerHTML=out.length?`<div class="staff-day-grid">${out.join("")}</div>`:'<div class="staff-schedule-empty"><strong>該当予定はありません</strong></div>';}
  ensureMonthlyScheduleUi_();
})();
