const API_URL="https://script.google.com/macros/s/AKfycbyvpQRxRpMRfpaQHtBar77dViCqPl-hdFW-2yMdozhN8RHtwcrFiNEM9cvEbny4x9q0/exec";
const state={staff:[],stores:[],services:[],serviceHours:[],selectedStaffCode:"",shiftRows:[],shiftPreview:null};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
async function apiGet(action,params={}){const u=new URL(API_URL);u.searchParams.set("action",action);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));u.searchParams.set("_",Date.now());const r=await fetch(u,{cache:"no-store"}),j=await r.json();if(!j.ok)throw new Error(j.message||"取得失敗");return j}
async function apiPost(p){const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(p)}),j=await r.json();if(!j.ok)throw new Error(j.message||"処理失敗");return j}
$$(".nav-button").forEach(b=>b.onclick=()=>{$$(".nav-button").forEach(x=>x.classList.toggle("is-active",x===b));$$(".view").forEach(x=>x.classList.remove("is-active"));$("#"+b.dataset.view+"View").classList.add("is-active")});
$$(".registration-card").forEach(b=>b.onclick=()=>showRegistration(b.dataset.registration));
async function showRegistration(type){["#staffManager","#shiftManager","#serviceHoursManager","#registrationPlaceholder"].forEach(x=>$(x)?.classList.add("is-hidden"));if(type==="staff"){$("#staffManager").classList.remove("is-hidden");await loadStaff();return}if(type==="shift"){$("#shiftManager").classList.remove("is-hidden");await Promise.all([loadStaff(),loadStores()]);setupShift();return}if(type==="hours"){$("#serviceHoursManager").classList.remove("is-hidden");await loadServices();setupServiceHours();return}const map={service:["🏷️","サービス登録"]},v=map[type]||["🛠️","準備中"];$("#placeholderIcon").textContent=v[0];$("#placeholderTitle").textContent=v[1];$("#registrationPlaceholder").classList.remove("is-hidden")}
async function loadStaff(){try{const j=await apiGet("getStaff",{include_inactive:"true"});state.staff=Array.isArray(j.data?.staff)?j.data.staff:Array.isArray(j.data)?j.data:[];renderStaff()}catch(e){state.staff=[];$("#staffList").innerHTML=`<div class="no-staff">${esc(e.message)}</div>`}}
async function loadStores(){try{const j=await apiGet("getStores");state.stores=Array.isArray(j.data)?j.data:[]}catch(e){msg(e.message,true)}}
function renderStaff(){const box=$("#staffList");if(!box)return;const q=($("#staffSearch")?.value||"").toLowerCase();const a=state.staff.filter(s=>[s.staff_code,s.staff_name,s.display_name,s.role].join(" ").toLowerCase().includes(q));box.innerHTML=a.map(s=>`<div class="staff-card"><span class="role-icon">${String(s.role).toUpperCase()==="TRAINER"?"🏋️":"👤"}</span><span class="staff-meta"><strong>${esc(s.display_name||s.staff_name||s.staff_code)}</strong><small>${esc(s.role||"")} · ${esc(s.store_code||"")}</small></span></div>`).join("")||'<div class="no-staff">該当するスタッフがいません。</div>'}
$("#staffSearch")?.addEventListener("input",renderStaff);
$$(".shift-tab").forEach(b=>b.onclick=()=>{$$(".shift-tab").forEach(x=>x.classList.toggle("is-active",x===b));$("#shiftBulkPanel").classList.toggle("is-hidden",b.dataset.shiftTab!=="bulk");$("#shiftSinglePanel").classList.toggle("is-hidden",b.dataset.shiftTab!=="single");hideMsg()});
function setupShift(){const stores=state.stores.filter(s=>s.active!==false),o=stores.map(s=>`<option value="${esc(s.store_code)}">${esc(s.store_name||s.store_code)} (${esc(s.store_code)})</option>`).join("");$("#shiftBulkStore").innerHTML=o;$("#shiftSingleStore").innerHTML=o;["#shiftBulkStore","#shiftSingleStore"].forEach(x=>{if(stores.some(s=>s.store_code==="YACHIYO"))$(x).value="YACHIYO"});$("#shiftSingleStaff").innerHTML=state.staff.filter(s=>s.active!==false).map(s=>`<option value="${esc(s.staff_code)}">${esc(s.display_name||s.staff_name||s.staff_code)} (${esc(s.staff_code)})</option>`).join("");const d=new Date(),ym=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;$("#shiftTargetMonth").value=ym;$("#shiftSingleDate").value=`${ym}-${String(d.getDate()).padStart(2,"0")}`}
function csvLine(line){const a=[];let s="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){s+='"';i++}else q=!q}else if(c===","&&!q){a.push(s);s=""}else s+=c}a.push(s);return a}
async function readCsv(f){const lines=(await f.text()).replace(/^\uFEFF/,"").split(/\r?\n/).filter(x=>x.trim());if(lines.length<2)throw new Error("CSVにデータがありません。");const h=csvLine(lines[0]).map(x=>x.trim()),req=["staff_code","date","start_time","end_time"];req.forEach(k=>{if(!h.includes(k))throw new Error(`CSVに ${k} 列がありません。`)});return lines.slice(1).map(l=>{const c=csvLine(l),o={};h.forEach((x,i)=>o[x]=String(c[i]??"").trim());return {staff_code:o.staff_code,date:o.date,start_time:o.start_time,end_time:o.end_time}})}
$("#shiftPreviewButton").onclick=async()=>{hideMsg();const f=$("#shiftCsvFile").files[0];if(!f)return msg("CSVファイルを選択してください。",true);try{state.shiftRows=await readCsv(f);const j=await apiPost({action:"previewStaffShiftImport",mode:$("#shiftImportMode").value,store_code:$("#shiftBulkStore").value,target_month:$("#shiftTargetMonth").value,rows:state.shiftRows});state.shiftPreview=j.data;renderPreview(j.data);$("#shiftImportButton").disabled=+j.data.error_count>0||+j.data.valid_count===0;msg(+j.data.error_count?"エラーがあります。CSVを修正してください。":"プレビューOKです。",+j.data.error_count>0)}catch(e){msg(e.message,true)}};
function renderPreview(d){$("#shiftPreviewArea").classList.remove("is-hidden");$("#shiftPreviewSummary").innerHTML=`<span>全 ${d.total_count}件</span><strong class="ok-count">有効 ${d.valid_count}件</strong><strong class="error-count">エラー ${d.error_count}件</strong>`;const em=new Map((d.errors||[]).map(x=>[+x.row,x]));$("#shiftPreviewBody").innerHTML=state.shiftRows.map((r,i)=>{const e=em.get(i+2),s=state.staff.find(x=>x.staff_code===r.staff_code);return `<tr class="${e?"row-error":""}"><td>${i+2}</td><td>${esc(s?.display_name||s?.staff_name||r.staff_code)}<small>${esc(r.staff_code)}</small></td><td>${esc(r.date)}</td><td>${esc(r.start_time)}</td><td>${esc(r.end_time)}</td><td>${e?`<span class="status-bad">${esc(e.message||e.code)}</span>`:'<span class="status-ok">OK</span>'}</td></tr>`}).join("")}
$("#shiftImportButton").onclick=async()=>{if(!state.shiftPreview||+state.shiftPreview.error_count)return msg("エラーのないプレビューを先に実行してください。",true);if(!confirm(`${$("#shiftTargetMonth").value} のシフト ${state.shiftRows.length}件を登録します。よろしいですか？`))return;try{const j=await apiPost({action:"importStaffShifts",mode:$("#shiftImportMode").value,store_code:$("#shiftBulkStore").value,target_month:$("#shiftTargetMonth").value,rows:state.shiftRows});msg(`登録完了：${j.data.inserted_count}件 / 無効化：${j.data.disabled_count}件`);$("#shiftImportButton").disabled=true}catch(e){msg(e.message,true)}};
$("#shiftSingleForm").onsubmit=async e=>{e.preventDefault();if($("#shiftSingleStart").value>=$("#shiftSingleEnd").value)return msg("終了時刻は開始時刻より後にしてください。",true);try{const j=await apiPost({action:"saveStaffShift",staff_code:$("#shiftSingleStaff").value,store_code:$("#shiftSingleStore").value,date:$("#shiftSingleDate").value,start_time:$("#shiftSingleStart").value,end_time:$("#shiftSingleEnd").value});msg(`保存しました：${j.data.date} ${j.data.start_time}〜${j.data.end_time}`)}catch(x){msg(x.message,true)}};
function msg(s,e=false){const n=$("#shiftMessage");n.textContent=s;n.classList.remove("is-hidden");n.classList.toggle("is-error",e)}function hideMsg(){$("#shiftMessage").classList.add("is-hidden")}
async function loadServices(){try{const j=await apiGet("getServices");state.services=Array.isArray(j.data?.services)?j.data.services:Array.isArray(j.data)?j.data:[]}catch(e){state.services=[];hoursMsg(e.message,true)}}
function setupServiceHours(){const a=state.services.filter(s=>s.active!==false),sel=$("#serviceHoursService");sel.innerHTML=a.map(s=>`<option value="${esc(s.service_code)}">${esc(s.service_name||s.name||s.service_code)} (${esc(s.service_code)})</option>`).join("");if(a.some(s=>String(s.service_code).toUpperCase()==="UNSUBSCRIBE"))sel.value="UNSUBSCRIBE";sel.onchange=loadSelectedHours;$("#newServiceHourButton").onclick=()=>{$("#serviceHourForm").classList.remove("is-hidden");$("#serviceHourDay").value="ALL";$("#serviceHourStart").value="";$("#serviceHourEnd").value="";hideHoursMsg()};$("#cancelServiceHourButton").onclick=()=>$("#serviceHourForm").classList.add("is-hidden");$("#serviceHourForm").onsubmit=saveHour;loadSelectedHours()}
async function loadSelectedHours(){const code=$("#serviceHoursService").value;if(!code){$("#serviceHoursList").innerHTML='<div class="empty-service-hours">サービスがありません。</div>';return}const s=state.services.find(x=>String(x.service_code)===code)||{};$("#serviceHoursTitle").textContent=s.service_name||s.name||code;$("#serviceHoursCode").textContent=code;try{const j=await apiGet("getServiceHours",{service_code:code});state.serviceHours=Array.isArray(j.data)?j.data:[];renderHours()}catch(e){hoursMsg(e.message,true)}}
function renderHours(){const label={ALL:"すべての曜日",SUN:"日曜日",MON:"月曜日",TUE:"火曜日",WED:"水曜日",THU:"木曜日",FRI:"金曜日",SAT:"土曜日"};const box=$("#serviceHoursList");if(!state.serviceHours.length){box.innerHTML='<div class="empty-service-hours">提供時間がまだ登録されていません。</div>';return}box.innerHTML=state.serviceHours.map((r,i)=>`<div class="service-hour-row"><div class="service-day"><strong>${label[r.day_of_week]||esc(r.day_of_week)}</strong><small>${esc(r.day_of_week)}</small></div><div class="service-time">${esc(r.start_time)} <span>〜</span> ${esc(r.end_time)}</div><button type="button" class="danger-ghost" data-i="${i}">削除</button></div>`).join("");$$(".danger-ghost[data-i]").forEach(b=>b.onclick=()=>deleteHour(state.serviceHours[+b.dataset.i]))}
async function saveHour(e){e.preventDefault();const start=$("#serviceHourStart").value,end=$("#serviceHourEnd").value;if(!start||!end)return hoursMsg("開始時刻と終了時刻を入力してください。",true);if(start>=end)return hoursMsg("終了時刻は開始時刻より後にしてください。",true);try{await apiPost({action:"saveServiceHour",service_code:$("#serviceHoursService").value,day_of_week:$("#serviceHourDay").value,start_time:start,end_time:end,active:true});$("#serviceHourForm").classList.add("is-hidden");await loadSelectedHours();hoursMsg("保存しました。")}catch(e2){hoursMsg(e2.message,true)}}
async function deleteHour(r){if(!confirm(`${r.day_of_week} ${r.start_time}〜${r.end_time} を削除しますか？`))return;try{await apiPost({action:"deleteServiceHour",service_code:r.service_code,day_of_week:r.day_of_week,start_time:r.start_time,end_time:r.end_time});await loadSelectedHours();hoursMsg("削除しました。")}catch(e){hoursMsg(e.message,true)}}
function hoursMsg(s,e=false){const n=$("#serviceHoursMessage");n.textContent=s;n.classList.remove("is-hidden");n.classList.toggle("is-error",e)}function hideHoursMsg(){const n=$("#serviceHoursMessage");n.classList.add("is-hidden");n.classList.remove("is-error")}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
(()=>{const n=$("#todayLabel"),d=new Date(),w=["日","月","火","水","木","金","土"];if(n)n.textContent=`${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")}（${w[d.getDay()]}）`})();
